# Generated by Django 2.1.7 on 2019-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasetimage',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='hparams_json_str',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='labels_json_str',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
