# Generated by Django 2.1.7 on 2019-06-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_auto_20190601_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='training_hparams_json_str',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
