# Generated by Django 2.1.7 on 2019-06-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_mlmodel_training_hparams_json_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='training_hparams_json_str',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
