# Generated by Django 2.1.7 on 2019-06-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_auto_20190601_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='learner_path',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='parameters_path',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
