# Generated by Django 2.1.7 on 2019-06-01 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_auto_20190601_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='snapshots_json_str',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
