# Generated by Django 2.1.7 on 2019-06-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='datasetimage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coreapp.DatasetImage'),
        ),
    ]
