# Generated by Django 2.1.7 on 2019-06-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_auto_20190601_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='count_labels_json_str',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='result',
            name='counts_json_str',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
